# permissions for end users to view etcds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: etcd-viewer-role
rules:
- apiGroups:
  - devops.my.domain
  resources:
  - etcds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - devops.my.domain
  resources:
  - etcds/status
  verbs:
  - get
