# permissions for end users to edit etcdrestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: etcdrestore-editor-role
rules:
- apiGroups:
  - devops.my.domain
  resources:
  - etcdrestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops.my.domain
  resources:
  - etcdrestores/status
  verbs:
  - get
