# permissions for end users to edit etcddumps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: etcddump-editor-role
rules:
- apiGroups:
  - devops.my.domain
  resources:
  - etcddumps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops.my.domain
  resources:
  - etcddumps/status
  verbs:
  - get
