
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - devops.my.domain
  resources:
  - etcddumps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops.my.domain
  resources:
  - etcddumps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - devops.my.domain
  resources:
  - etcdrestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops.my.domain
  resources:
  - etcdrestores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - devops.my.domain
  resources:
  - etcds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops.my.domain
  resources:
  - etcds/status
  verbs:
  - get
  - patch
  - update
